on:
  workflow_call:
    inputs:
      topolvm_version:
        description: "TopoLVM version"
        default: "devel"
        type: string
      image_tag:
        description: "Image tag"
        default: "latest"
        type: string
      image_prefix:
        description: "Image prefix"
        default: ""
        type: string
      push:
        description: "Push images"
        default: "false"
        type: string

jobs:
  build-images:
    name: "build-images"
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: true
      matrix:
        image:
          - "normal"
          - "with-sidecar"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login registry
        if: ${{ inputs.push == 'true' }}
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: make multi-platform-image-${{ matrix.image }}
        env:
          TOPOLVM_VERSION: ${{ inputs.topolvm_version }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          IMAGE_PREFIX: ${{ inputs.image_prefix }}
          PUSH: ${{ inputs.push }}
