on:
  workflow_call:
    inputs:
      topolvm_version:
        description: "TopoLVM version"
        default: "devel"
        type: string
      image_tag:
        description: "Image tag"
        default: "latest"
        type: string
      image_prefix:
        description: "Image prefix"
        default: ""
        type: string
      push:
        description: "Push images"
        default: "false"
        type: string

jobs:
  build-images:
    name: "build-images"
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: true
      matrix:
        image:
          - "normal"
          - "with-sidecar"
    steps:
      - name: Disk cleanup
        run: |
          # These code are copied from the following code:
          # https://github.com/shiguredo-webrtc-build/webrtc-build/blob/5a821e430b496bbff74cf45bab058ab4ac340c2c/.github/workflows/build.yml#L138-L147
          #    LICENSE: http://www.apache.org/licenses/LICENSE-2.0
          #    Copyright 2019-2025, Shiguredo Inc.
          df -h
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          df -h
      - uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login registry
        if: ${{ inputs.push == 'true' }}
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: make multi-platform-image-${{ matrix.image }}
        env:
          TOPOLVM_VERSION: ${{ inputs.topolvm_version }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          IMAGE_PREFIX: ${{ inputs.image_prefix }}
          PUSH: ${{ inputs.push }}
