name: "e2e-k8s-daemonset-lvmd"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
  push:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
    branches:
      - "main"
jobs:
  e2e-k8s-daemonset-lvmd:
    name: "e2e-k8s-daemonset-lvmd"
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: false
      matrix:
        kubernetes_versions: ["1.25.3", "1.24.7", "1.23.13"]
    env:
      KUBERNETES_VERSION: ${{ matrix.kubernetes_versions }}
      STORAGE_CAPACITY: "true"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: cache go dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('go.sum', 'Makefile') }}
          restore-keys: |
            go-
      - name: cache e2e sidecar binaries
        uses: actions/cache@v3
        with:
          path: |
            e2e/tmpbin
          key: e2e-sidecars-${{ hashFiles('csi-sidecars.mk') }}
          restore-keys: |
            e2e-sidecars-
      - name: install dependencies of minikube
        run: |
          # These tools are required to use minikube for Kubernetes v1.24+

          # For CNI plugins, see https://github.com/Mirantis/cri-dockerd/blob/v0.2.6/README.md#important
          CNI_PLUGINS_VERSION="v1.1.1"
          curl -L -o cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/${CNI_PLUGINS_VERSION}/cni-plugins-linux-amd64-${CNI_PLUGINS_VERSION}.tgz
          sudo mkdir -p /opt/cni/bin
          sudo tar -C /opt/cni/bin -xzf cni-plugins.tgz

          # Install cri-docker
          git clone -n https://github.com/Mirantis/cri-dockerd
          CRI_DOCKERD_VERSION="v0.2.6"
          cd cri-dockerd
          git checkout ${CRI_DOCKERD_VERSION}
          mkdir bin
          go get && go build -o bin/cri-dockerd
          mkdir -p /usr/local/bin
          sudo install -o root -g root -m 0755 bin/cri-dockerd /usr/local/bin/cri-dockerd
          sudo cp -a packaging/systemd/* /etc/systemd/system
          sudo sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service

          # This is a workaround for the following issue.
          # https://github.com/kubernetes/minikube/issues/15265
          sudo ln -s /usr/local/bin/cri-dockerd /usr/bin/cri-dockerd

          sudo systemctl daemon-reload
          sudo systemctl enable cri-docker.service
          sudo systemctl enable --now cri-docker.socket

          CRICTL_VERSION="v1.25.0"
          curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/$CRICTL_VERSION/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz --output crictl-${CRICTL_VERSION}-linux-amd64.tar.gz
          sudo tar zxvf crictl-$CRICTL_VERSION-linux-amd64.tar.gz -C /usr/local/bin
      - run: make -C e2e setup
      - run: make -C e2e daemonset-lvmd/create-vg
      - run: make -C e2e daemonset-lvmd/setup-minikube
      - run: make -C e2e daemonset-lvmd/launch-minikube
      - run: make -C e2e daemonset-lvmd/test
