name: "Main"
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  build:
    name: "build"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: cache go dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('go.sum', 'Makefile') }}
          restore-keys: |
            go-
      - run: make setup
      - run: make check-uncommitted
      - run: make test
      - run: make groupname-test
      - run: sudo -E env PATH=${PATH} go test -count=1 -race -v ./lvmd ./driver ./filesystem

  build-images:
    name: "build-images"
    needs: build
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: true
      matrix:
        image:
          - "normal"
          - "with-sidecar"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: make setup-docker-buildx
      - run: make multi-platform-image-${{ matrix.image }}

  container-structure-test:
    name: "container-structure-test"
    needs: build
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: true
      matrix:
        image:
          - "normal"
          - "with-sidecar"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: make install-container-structure-test
      - run: make image-${{ matrix.image }}
      - run: make container-structure-test STRUCTURE_TEST_TARGET=${{ matrix.image }}

  example:
    name: "example"
    runs-on: "ubuntu-20.04"
    defaults:
      run:
        working-directory: "example"
    strategy:
      fail-fast: false
      matrix:
        use_legacy: ["", "true"]
    env:
      USE_LEGACY: ${{ matrix.use_legacy }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: cache go dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('go.sum', 'Makefile') }}
          restore-keys: |
            go-
      - run: make setup
      - run: make run BUILD_IMAGE=true
